import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});


// src/app/layout.ts

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className="bg-[#0f172a] min-h-screen">
        <Navbar />
        {children}
      </body>
    </html>
  );
}